### ISSUE TITLE
Allow custom error messages / output to display validation errors for failed submissions

### ISSUE THREAD

**Issue by MoritzLost** [engram-design/Workflow#139] opened 2021-10-18 15:16 UTC
**What are you trying to do?**

I'm using a hook to prevent submissions if any required fields on the entry are empty (this is possible by default since required fields aren't validated for drafts). Here's the hook I'm using, which does work fine:

```php
// module init
Event::on(
    Submission::class,
    Submission::EVENT_BEFORE_SAVE,
    [$this, 'validateRequiredFields']
);

// hook method
public function validateRequiredFields(ModelEvent $e)
{
    /** @var \verbb\workflow\elements\Submission $submission */
    $submission = $e->sender;
    /** @var \craft\elements\Entry $entry */
    $entry = $submission->getOwner();

    $entry->setScenario(Entry::SCENARIO_LIVE);
    $entryIsFullyValid = $entry->validate();
    if (!$entryIsFullyValid) {
        $e->isValid = false;
    }
}
```

The problem is that there's no way to specify error messages for the editor to fix – the only indication they get is the generic *Could not submit for approval* message. The errors also aren't displayed in the main editor. I need some way to display additional information (in this case, a list of errors) to the editor so they know what to fix.

**What's your proposed solution?**

I can think of two ways to allow custom error messages:

- Add [template hooks](https://craftcms.com/docs/3.x/extend/template-hooks.html) in the sidebar template (for example, above the submission form)  so I can use the submission to get to the owner and display my own error messages.
- Add a property for errors to the `Submission` model that I can use inside the hook to add errors, and adjust the template to display those errors. Then my hook could do something like this:

```php
$submission->addError('owner', 'The following validation errors prevent the submission: …');
```

**Additional context**

Another related issue: The submission form doesn't retain the editor notes if the submission fails, which is annoying because the editor then has to type in the notes again. The Submissions services already [sets the failed submission as a route parameter](https://github.com/verbb/workflow/blob/craft-3/src/services/Submissions.php#L131-L133), so this could be fixed by checking if this parameter exists in the editor template and passing the submitted notes as `value` to `{{ forms.textareaField }}` ([here, for instance](https://github.com/verbb/workflow/blob/craft-3/src/templates/_includes/editor-pane.html#L32-L40)).

**Comment by engram-design** [comment] 2021-10-19 11:43
So a submission should enforce validation before submitting it for review, is that not doing that? You shouldn't need to enforce it yourself, as Workflow should do that (last I checked, but drafts have gone through so many updates/changes).

I'm wondering if you can use the same template hook Workflow does `cp.entries.edit.details` to add your content there?

Adding model-level errors might work, I'll need to test this.

As for the notes, that's potentially fixable, I'll look into that. As you mention I _think_ it should be pretty easy.

**Comment by MoritzLost** [comment] 2021-10-19 12:54
@engram-design Thanks for the reply!

> So a submission should enforce validation before submitting it for review, is that not doing that? You shouldn't need to enforce it yourself, as Workflow should do that (last I checked, but drafts have gone through so many updates/changes).

Yes, that's what I'm trying to do. At least in my test installation, the submission for an unpublished draft goes through even if required fields are left empty, and no validation errors are displayed in the entry form. I just assumed that's how it's supposed to work, since the submitted entry is still a draft and required fields are ignored when saving drafts. But if required fields are supposed to be validated before the submission goes through – yeah then it's probably a bug.

I'm using all the current versions:

- Craft 3.7.16
- Workflow 1.6.4
- PHP 8.0.9
- MySQL 8.0.26

> I'm wondering if you can use the same template hook Workflow does cp.entries.edit.details to add your content there?

I tried that, couldn't get it to work though because I didn't find a way to access the validated submission or the related entry (with the validation errors). I tried to add those as route params (see below), but they're still not present in the `$context` passed to the hook.

```php
public function validateRequiredFields(ModelEvent $e)
{
    /** @var \verbb\workflow\elements\Submission $submission */
    $submission = $e->sender;
    /** @var \craft\elements\Entry $entry */
    $entry = $submission->owner;

    $entry->setScenario(Entry::SCENARIO_LIVE);
    $entryIsFullyValid = $entry->validate();
    if (!$entryIsFullyValid) {
        $e->isValid = false;
        Craft::$app->getUrlManager()->setRouteParams([
            'failedSubmission' => $submission,
            'failedEntry' => $entry,
        ]);
    }
}
```

Maybe I'm doing something wrong? I could *probably* make this work by re-doing the validation in the hook or putting the errors in some shared state … but feels like I'm missing something here.

> Adding model-level errors might work, I'll need to test this.

That would be great – even if this specific use-case can be solved using the hooks above, having the ability to add model errors that automatically show up in the form would be very helpful!

> As for the notes, that's potentially fixable, I'll look into that. As you mention I think it should be pretty easy.

Thanks!

**Comment by MoritzLost** [comment] 2021-11-03 11:56
@engram-design Were you able to test one of the solutions yet, like adding model-level errors? And can you confirm if the current behaviour (required fields not being validated before submissions) is working as intended or a bug?

The site I'm working on is soon launching, so would be good to know if/when this bug (if it is one) will be fixed, so I know how much effort I should put into developing a workaround :)
Thanks!

**Comment by engram-design** [comment] 2021-11-03 12:43
@MoritzLost I haven't had a chance to properly test this all out yet sorry, but I should be able to do so over the weekend.

**Comment by engram-design** [comment] 2021-11-06 07:15
So firstly, you shouldn't be able to submit an entry for review without the required fields being set. That appears to be a regression with Workflow, which I've now fixed.

Now the problem with the adding errors to the submission model, is that the draft entry is saved successfully, but then you're flagging in your event that the Submission fails - which is fine. However we can't add errors to the entry element because it's already passed validation. Essentially - it's too late by the time the event is called for us to take any action.

Even if we were to use something like `$submission->addError('owner', 'The following validation errors prevent the submission: …');` which could of course be done, we'd have to place them somewhere.

As for the notes disappearing, that's really down to how you're triggering the event in your module, and the complications of how we save a submission (using the `Entry::EVENT_AFTER_SAVE` event). Again, it's because it's happening too late in the process. However, I believe I've also fixed an issue with this.

If you can give [1.6.5](https://github.com/verbb/workflow/releases/tag/1.6.5) a go when you can.

**Comment by MoritzLost** [comment] 2021-11-10 12:53
@engram-design Awesome, thank you very much! Now that the module validates required fields again before allowing the submission, everything falls into place. Validation errors on the entry are now displayed normally, which is great. Restoring the notes input if the validation fails is a great improvement as well!

Model errors on the Submission model would still be nice to have – maybe display them below the text input, or below the submit button?

Anyway, for my current use-case this issue is firmly solved, thanks again!

**Closed as completed** 2022-11-04 01:38 UTC
Labels: feature request
