### ISSUE TITLE
Required notes validation not applying to draft entries

### ISSUE THREAD

**Issue by mark-adigital** [engram-design/Workflow#59] opened 2019-03-20 14:33 UTC
Hey Josh - think I've spotted an issue where the Editor/Publisher Submission Notes Required setting validation isn't applied when the entry is a draft but does work on the live entry. I've observed this on an install running Workflow 1.1.8 and Craft 3.1.19. Cheers!

**Comment by engram-design** [comment] 2019-03-22 04:59
Yeah, its a known issue. The problem is that the `beforeSaveDraft` event isn't actually cancellable like the `beforeSaveEntry` is. I might need to ping the Craft crew about an amendment.

**Comment by mark-adigital** [comment] 2019-03-22 10:47
Ah - makes sense. Thanks for chasing it up with P&T.

**Comment by engram-design** [comment] 2019-03-22 23:08
Fixed in [1.1.9](https://github.com/verbb/workflow/releases/tag/1.1.9)

**Closed as completed by engram-design** 2019-03-22 23:08 UTC

**Comment by mark-adigital** [comment] 2019-03-25 10:01
Looks good, thanks!
