### ISSUE TITLE
Random Neo fields from entry are used as entry reference

### ISSUE THREAD

**Issue by elfacht** [engram-design/Workflow#216] opened 2024-08-15 09:27 UTC
### Describe the bug

An entry with multiple tabs (field layout) and Neo fields would be sometimes saved with a random field inside of such Neo fields in the submission. The entry title of the submission is empty then. This happens after clicking the content tabs of an entry before the submission.

![Screen shot 2024-08-15 um 11 23 41](https://github.com/user-attachments/assets/425d8808-bd37-40fb-93f8-d70ac2ed67c1)

![Screen shot 2024-08-15 um 11 21 03](https://github.com/user-attachments/assets/f73f2b76-f4cc-4d6f-837e-de72eaafaa3c)

### Steps to reproduce

1. As an editor: Edit an entry (create a draft) that has multiple tabs in the field layout and a Neo field with nested fields.
2. Before the submission click any tab of that entry.
3. Save and see the empty title and wrong entry reference in the submission list.

### Craft CMS version

5.2.9

### Plugin version

3.0.2

### Multi-site?

No

**Comment by engram-design** [comment] 2024-08-20 02:01
I can't seem to replicate that I'm afraid. You mention that this happens "sometimes", does that mean it's sporadic?

For me, any submission is always in reference to the outer entry, and not the Neo block, which seems to be the case here.

If you're able to, a video reproduction would be amazing on this!

**Comment by elfacht** [comment] 2024-08-20 06:00
Hi @engram-design, I made a video and it occurs even without clicking the tabs. It seems that random Neo or Matrix fields from the field layout are taken as a reference.

https://github.com/user-attachments/assets/440657a5-8ca5-48cb-ab05-3d64b393cc78

 This was also my first take for this video. You can see here how often it happens (that's all page edits, not block edits):

![Screen shot 2024-08-20 um 08 02 49](https://github.com/user-attachments/assets/b687559d-9686-4ef1-a57f-69cecd0e683f)

**Comment by engram-design** [comment] 2024-08-27 12:39
Might be related to https://github.com/verbb/workflow/issues/217 if you want to test the same fix, run `composer require verbb/workflow:"dev-craft-5 as 3.0.2"`.

**Comment by elfacht** [comment] 2024-09-04 07:19
@engram-design This seems to work, thanks!

**Comment by engram-design** [comment] 2024-09-07 11:57
Fixed in [3.0.3](https://github.com/verbb/workflow/releases/tag/3.0.3)

**Closed as completed by engram-design** 2024-09-07 11:57 UTC
